"""One-off generator: extract Flex Message contents JSON from the original DSL YAML
and produce sql/init.sql with seed rows.

Run once:
    python _generate_init.py
"""
from __future__ import annotations

import json
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[2]
DSL = ROOT / "DSL" / "Line_多選項連動助理_涵蓋所有FLEX_MESSAGE功能.yml"
OUT = pathlib.Path(__file__).with_name("init.sql")


def extract_contents() -> dict:
    data = yaml.safe_load(DSL.read_text(encoding="utf-8"))
    nodes = data["workflow"]["graph"]["nodes"]
    http_node = next(n for n in nodes if n["data"].get("type") == "http-request")
    body_items = http_node["data"]["body"]["data"]
    raw_text = next(item["value"] for item in body_items if item["type"] == "text")
    payload = json.loads(raw_text)
    return payload["messages"][0]["contents"]


def sql_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "''")


def main() -> int:
    contents = extract_contents()
    contents_json = json.dumps(contents, ensure_ascii=False, separators=(",", ":"))

    sql = f"""-- Auto-generated by flex-api/sql/_generate_init.py
-- Creates line_flex database, flex_api user, flex_message_templates table and seed rows.

CREATE DATABASE IF NOT EXISTS line_flex
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'flex_api'@'%' IDENTIFIED BY 'flex_api_pwd_change_me';
GRANT SELECT, INSERT, UPDATE, DELETE ON line_flex.* TO 'flex_api'@'%';
FLUSH PRIVILEGES;

USE line_flex;

CREATE TABLE IF NOT EXISTS flex_message_templates (
  id           VARCHAR(64)  NOT NULL PRIMARY KEY,
  description  VARCHAR(255) NULL,
  contents     JSON         NOT NULL,
  created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS line_channels (
  name                  VARCHAR(64)  NOT NULL PRIMARY KEY,
  channel_access_token  TEXT         NOT NULL,
  default_user_id       VARCHAR(64)  NOT NULL,
  description           VARCHAR(255) NULL,
  created_at            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO line_channels (name, channel_access_token, default_user_id, description) VALUES
('default',
 'xv7a1j7jR8o22tgsLvOYfVwEhsKo2N29ru7zHDAUUKLih21/zHB/nZqzbQ+VG54teKPFypCmZmHi0MpP34A8Xma0Hc1pwkGAzGtGs1YVjYhU2672ScJt0mObFXMJxae5ZIkC8fGByIkMyMY6853k9QdB04t89/1O/w1cDnyilFU=',
 'Uc83af6e58fd43c6da36a9285435a82e0',
 'main LINE bot (migrated from DSL env vars)')
ON DUPLICATE KEY UPDATE
  channel_access_token = VALUES(channel_access_token),
  default_user_id      = VALUES(default_user_id),
  description          = VALUES(description);

INSERT INTO flex_message_templates (id, description, contents) VALUES
('all_elements_demo',
 'Flex Message 完整功能展示（Text/Span/Icon/Image/Video/Layout/Button/Separator/Padding）',
 '{sql_escape(contents_json)}')
ON DUPLICATE KEY UPDATE
  description = VALUES(description),
  contents    = VALUES(contents);
"""
    OUT.write_text(sql, encoding="utf-8")
    print(f"Wrote {OUT} ({len(sql)} bytes, contents JSON {len(contents_json)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
